### ISSUE TITLE
Add progress reporting showing statistics on total rules parsed, completed, matched, and failed

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#132]
I think it'd be great to have this in the alpha release.

**Comment by shawn-hurley** [comment]
are you thinking metrics?

**Comment by pranavgaikwad** [comment]
@shawn-hurley no, if someone is looking at the logs, they should get a feel of how much work is done so far, and how much is remaining

**Comment by eemcmullan** [comment]
@pranavgaikwad Is this something I could work on?

**Comment by shawn-hurley** [comment]
All yours!

**Comment by shawn-hurley** [comment]
Adding to Demo E if you are working on it!
