### ISSUE TITLE
CLI flag options to state scope of analysis

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#136]
These options are what I am currently thinking we need for the scope of analysis. 

1. Full analysis - will analyze all deps and source code.
2. Skip Deps - will only analyze the source code
3. Partial analysis - a hybrid, where a provider (if supported) can decide certain deps that are interesting (say not known open source projects) and that these should be ignored.

**Comment by pranavgaikwad** [comment]
@shawn-hurley I like this idea

**Comment by shawn-hurley** [comment]
closed by #189
