### ISSUE TITLE
External Provider Settings Rework

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#142]
So, I believe that we will need to update the settings structures and what and how the flow of information goes.

1. I believe that the provider_settings that we know of today, SHOULD just point to the GRPC servers that are running. There should be a defined file to look at(provider_settings), and each provider should append to this file. When the servers start up, it should be responsible for dealing with this file, we should write the helper to do this on server start.

The new Provider Setting struct should look like

```golang

type ProviderConfig struct {
    Address string (localhost:17902 or something)
    Capabilities []Caps (will have the OPENAPISCHEMA)
    Name string (go, java etc)
}

```

The GRPC interface, will remove the Capabilities Calls, as this will be cached based on the config above.

The GRPC Server settings file will have:

```golang
type ServerConfig struct {
  BinaryLocation string
   ProviderSpecificConfig map[string]string
}
```

**GRPC Server should have a hard coded name**

2. Each GRPC server, will need to know some information that we have captured in the config. I think here we have a decision to make.
            1. We can assume that a given provider, will only work for a single project (location/dependencyPath of the source). This will mean that when we start up the the GRPC server we just add these to the ServerConfig.
            2.  We have a concept of a provider server running for a long time, over the course of many analysis, and have to add location/dependencyPath to the INIT call, and we will have to have concurrent inited projects. This will mean more complexity in the server, and the client will have to have some value to send back and forth w/ the server to tell which inited server to use. 
            
I would love to push off 2, but I think it changes the interface for the config files and the GRPC service, and I don't want to have to do a v2 quickly. 

I am of the opinion that we should do 2 even thought it will be more work, as I think that it allows for some interesting architectures of providers in the future. (maybe a ML server, so that it does not have start up cost is an example)

**Comment by shawn-hurley** [comment]
After discussion with Fabian and after the review I think we came to two conclusions
1. The provider_settings needs to have a path to the GRPC Server binary. then It will also have all the other things to init..
2. The Server/Client that we are writing are going to responsible for having **something* that allows for multiple inited projects. 

So Rough Sketch of the new Provider Config Struct

```golang
type ProviderConfig struct {

   Name string
   BinaryPath string (ABS path to the binary)
   Address string (optional address, to a running Server, ONE OF BinaryPath or Address MUST be set)
   InitConfig InitConfig 
} 

type InitConfig struct {
      LSPServerPath string
      ProviderSpecificConfig map[string]string
}
```

Looking for a rough ack from @fabianvf and @pranavgaikwad to move forward with this approach to settings re-write and will update the open PR.

**Comment by fabianvf** [comment]
ACK sounds good to me

**Comment by pranavgaikwad** [comment]
@shawn-hurley sounds good to me

**Comment by pranavgaikwad** [comment]
@shawn-hurley are we good to close this?

**Comment by shawn-hurley** [comment]
I believe so, there may need to be follow ups but the base work should be done
