### ISSUE TITLE
Deduplication of Incidents Per rule

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#144]
If a rule has an incident that has the exact same file/line number, we should only keep one of these, currently, we keep all of them.

**Comment by shawn-hurley** [comment]
To implement this, when creating violations, we should have a map of URI-linenumber, that we can say to ignore and skip creating violations for things that have already been found.

**Comment by Chanakya-TS** [comment]
incidents can have the same uri but different message, line number etc. cannot have a map of uri, need to be able to compare incident structs to stop duplicates

**Comment by shawn-hurley** [comment]
The serialization cost is probably expensive I wonder if there is a way to compare just URI and resolved message

**Comment by pranavgaikwad** [comment]
`fmt.Sprintf("%s-%s-%s", fileURI, messageHash, lineNumber)` isn't too bad for the map key

**Comment by Chanakya-TS** [comment]
there are incidents with minute differences such as the following one, so just fileURI, messageHash and lineNumber wont be sufficient.

![Image](https://github.com/konveyor/analyzer-lsp/assets/66557279/73dd6445-a0ae-4022-b5e1-c209fe93e91c)

**Comment by shawn-hurley** [comment]
I might have a different opinion than others, but if that is found by the same rule, I think only one of them being a violation is fine IMOOn May 17, 2023, at 5:22 PM, Chanakya-TS ***@***.***> wrote:﻿
there are incidents with minute differences such as the following one, so just fileURI, messageHash and lineNumber wont be sufficient.
