### ISSUE TITLE
Do not fail when dependency SHA cannot be read from file

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#175]
Right now, we fail and return if any one dependency SHA cant be found. We need to continue looking at other deps.

**Comment by shawn-hurley** [comment]
you can find this code specifically for the java provider here:
https://github.com/konveyor/analyzer-lsp/blob/main/provider/internal/java/dependency.go#L202

**Comment by pranavgaikwad** [comment]
@punithnayak thank you! please take it away

**Comment by punithnayak** [comment]
Hey @pranavgaikwad 
![image](https://github.com/konveyor/analyzer-lsp/assets/110713318/3d0aea16-35e2-4778-9db1-b42d5e14193a)
Facing this issue

**Comment by punithnayak** [comment]
Hey @pranavgaikwad can you please tell  me how resolve this issue

**Comment by shawn-hurley** [comment]
I think that you need to add docker.io as a registry

**Comment by pranavgaikwad** [comment]
Fixed via #272
