### ISSUE TITLE
Allow all builtin types to handle file paths from files

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#187]
Currently, only XML can handle file paths from the `files` condition.

We should make this a library function such that other providers can also determine if the field is in the template, and if so, automatically pull out the file paths and give them an `[]string` 

You can find the file condition code here: https://github.com/konveyor/analyzer-lsp/blob/main/provider/internal/builtin/service_client.go#L75-L127

you can see the example of XML: https://github.com/konveyor/analyzer-lsp/blob/main/provider/internal/builtin/service_client.go#L135-L145

I believe that we should consider the library function living in provider.go here:
https://github.com/konveyor/analyzer-lsp/blob/main/provider/provider.go

**Comment by krishnaduttPanchagnula** [comment]
Hi @shawn-hurley  i would like to take this up, can you please where this files condition is?

**Comment by shawn-hurley** [comment]
@krishnaduttPanchagnula updated the issue with more information on where to go to look for stuff, if you want more help we can try to find a time in your TZ to meet up?

**Comment by krishnaduttPanchagnula** [comment]
@shawn-hurley surely , are you free between 9-12 pm IST this friday, i not sure what would that translate to in your time zone  ? We can work that out if it fine with you.

**Comment by shawn-hurley** [comment]
It converts to around `7am` for the 12pm, I can do that, but probably not on friday does next tuesday work?

**Comment by krishnaduttPanchagnula** [comment]
Yup @shawn-hurley  sounds good to me

**Comment by shawn-hurley** [comment]
If it still works, Please email me at shurley @ redhat.com so I can send an meeting invite!
