### ISSUE TITLE
Consider moving lspServerPath to providerSpecificConfig

### ISSUE THREAD

**Issue by djzager** [konveyor/analyzer-lsp#198]
Link to relevant [slack conversation](https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1686167624905009?thread_ts=1686159109.450979&cid=C04QZJFQ0UA).

Main idea is that it may be better to let each provider handle the path (and how to invoke) the language server, and if a provider decides they want to allow the path to be overridden, they can handle that too.

**Comment by shawn-hurley** [comment]
@pranavgaikwad Adding this as I think we need to do this before we V1 the API for the config
