### ISSUE TITLE
Parameter interpolation not working properly sometimes

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#219]
There are several rules with single or multiple `where` clauses which don't seem to be working properly. See for instance [this group of rules in the Failing rules doc](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A85) or [this one](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A30).

**Comment by shawn-hurley** [comment]
As far as I can tell, the problem here is the regex:

for instance:
https://regex101.com/r/FiGJAK/1

If we update the regex to be correct I would expect this to work, but currently, the custom variable is not being found so it can't be replaced.

**Comment by shawn-hurley** [comment]
@pranavgaikwad I believe that we need fix this in our rule sets, is now a good time to work on this?
