### ISSUE TITLE
Inconsistent behaviour of * in javaclass

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#220]
When looking for a pattern, for instance:
```java
import java.sql.BatchUpdateException;
```
the following rule pattern will work:
```yaml
pattern: java.*.BatchUpdate*
```
but not the following:
```yaml
pattern: java*BatchUpdate*
```
It seems to be an issue with the handling of dots in the target pattern.

**Comment by shawn-hurley** [comment]
I think that this is the correct behavior for regex, I don't believe that this needs fixing. 

https://regex101.com/r/29gyuk/1

**Comment by jmle** [comment]
@shawn-hurley @pranavgaikwad I can't remember exactly why I created this, but it can probably be closed

**Comment by shawn-hurley** [comment]
Closing
