### ISSUE TITLE
Handle public-id field in xmlfile conditions

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#221]
The `public-id` field in `xmlfile` conditions indicates the [Formal Public Identifier](https://en.wikipedia.org/wiki/Formal_Public_Identifier) of the DTD, and it's present in [some windup rules](https://docs.google.com/spreadsheets/d/19_dL8ZiBu0ULghVdpLsx0zBhF8DcGnjwMwslIcQytoU/edit#gid=372217138&range=A143) which are currently failing.

**Comment by aufi** [comment]
I'm going to work on this.
