### ISSUE TITLE
Dep.ResolvedIdentitier marshalled as 'sha'.

### ISSUE THREAD

**Issue by jortel** [konveyor/analyzer-lsp#231]
I suspect this is an oversight.

[violations.go#L101](https://github.com/konveyor/analyzer-lsp/blob/main/output/v1/konveyor/violations.go#L101)

**Comment by pranavgaikwad** [comment]
@jortel This is a non-issue. SHA is renamed to ResolvedIdentifier because in some cases (such as deps coming from embedded jars) we are not able to guarantee a valid SHA. Also the values differ for different providers. Anything I may have missed? @fabianvf
