### ISSUE TITLE
Add jaeger to image so it runs out of the box

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#236]
There are two changes needed - one in demo docker, and another one in base image. In the demo docker file, we need to do two things...first, run jaeger prior to running the analyzer...second, after analyzer finishes, make a request to jaeger to download the traces as json. These changes will go in the `demo.Dockerfile`. In the base image, we only need to include jaeger, i.e. the first step.

**Comment by Parthiba-Hazra** [comment]
HI @pranavgaikwad I placed a pr on this ..please checkout.
