### ISSUE TITLE
Probably need to remove Type, as that functionality is handled via labels

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#248]
https://github.com/konveyor/analyzer-lsp/blob/2fee76eb8e4f7bdc7a12546873f113395503f56c/output/v1/konveyor/violations.go#L99C4-L99C4

**Comment by pranavgaikwad** [comment]
@RipulHandoo do you know if the `Type` field is set or used anywhere in the source code?

**Comment by pranavgaikwad** [comment]
@RipulHandoo just search in the codebase where Type is used. Meanwhile, I will speak with other teams leveraging the API and check if they are using it and it'd break them. Will respond here in some time.

**Comment by RipulHandoo** [comment]
@pranavgaikwad 
Ok. Let me know.

**Comment by AdiAkhileshSingh15** [comment]
@pranavgaikwad 
After going through the source code, I found that the usage of `Type` field was minimal. Its primary use seemed to involve passing it to the dependency struct of either the service client or server. Following your suggestion, if labels can fulfill its functionality, removing `Type` from these sections is achievable. However, as `Type` field was used in the gRPC server's dependency struct, removing it requires rebuilding the gRPC server after making required changes in the protobuf file and subsequently implementing these changes within the client and provider server.
