### ISSUE TITLE
Add code snippets to JSON and XML in builtin provider

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#254]
It'd be great to have code locations in JSON and XML capabilities too similar to what I did in #253

**Comment by djzager** [comment]
Motivation for calling this a feature and not a bug fix revolves around the fact that the jsonquery and xmlquery libraries we are currently using do not track the location of nodes in the xml/json documents they are working with. Finding the location of a node matching some xml/json query is not immediately obvious.

We could: 
1. Write our own XML/JSON parser to keep track of nodes, implement location tracking, and get code snippets that way.
1. Submit patches to the xmlquery and json query deps.

It's not immediately obvious that this is a huge ask from our user base. Currently rating this as an important long-term feature.
