### ISSUE TITLE
We should probably only evaluate custom variables in code location's start and end range

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#258]
Right now, we match the entire code snip which leaves some room for error if there's something else matching that's not actually just added for context in code snippet.

**Comment by pranavgaikwad** [comment]
Possible duplicate of https://github.com/konveyor/analyzer-lsp/issues/219

**Comment by Parthiba-Hazra** [comment]
Hi @pranavgaikwad 
I think to resolve this, if we modify the [for-loop](https://github.com/konveyor/analyzer-lsp/blob/86939ecab164ddd71288499fa68400622cf509c9/engine/engine.go#L524) like this will be good to go .. let me know if I am wrong-- 
`withinRange := false
		for scanner.Scan() {
			if lineNumber == m.CodeLocation.StartPosition.Line {
				withinRange = true
			}
			if withinRange {
				if lineNumber == m.CodeLocation.EndPosition.Line {
					withinRange = false
				}
				codeSnip = codeSnip + fmt.Sprintf("%*d  %v\n", paddingSize, lineNumber+1, scanner.Text())
			}
			lineNumber += 1
		}`
