### ISSUE TITLE
Add validation on provider names

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#273]
Since we are now integrating external providers, we should have validations on provider names such that there are no duplicates. We should fail right away before initializing any of the providers if we find duplicates in provider config.

**Comment by Parthiba-Hazra** [comment]
Hey @pranavgaikwad 
I submitted a pr on this can you please check out..

**Comment by pranavgaikwad** [comment]
Fixed via #275
