### ISSUE TITLE
We shouldn't look for JARs in target directory when we already get a valid dep list from pom.xml

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#279]
When we find valid dep list from a pom.xml we should not be looking at JARs under target directory as they may just be duplicates generated from a build.

**Comment by Parthiba-Hazra** [comment]
@pranavgaikwad if I'm not wrong the issue associated with [GetDependenciesDAG()](https://github.com/konveyor/analyzer-lsp/blob/7ebd2f5efb3fbfbb5e102d80e8481ee823fdb3b2/provider/internal/java/dependency.go#L146) function, [here](https://github.com/konveyor/analyzer-lsp/blob/7ebd2f5efb3fbfbb5e102d80e8481ee823fdb3b2/provider/internal/java/dependency.go#L198) we are calling `discoverDepsFromJars()` function after getting dep list from pom.xml file.. 
so if [pomDeps](https://github.com/konveyor/analyzer-lsp/blob/7ebd2f5efb3fbfbb5e102d80e8481ee823fdb3b2/provider/internal/java/dependency.go#L189C2-L189C9) is empty then we are calling `GetDependencyFallback()` function [here](https://github.com/konveyor/analyzer-lsp/blob/7ebd2f5efb3fbfbb5e102d80e8481ee823fdb3b2/provider/internal/java/dependency.go#L61) so calling the `discoverDepsFromJars()` function is not needed in `GetDependenciesDAG()` function.

**Comment by Parthiba-Hazra** [comment]
Hi @pranavgaikwad I want to work on this issue. Can you confirm, am I right or nor on the upper comment?

**Comment by pranavgaikwad** [comment]
@Parthiba-Hazra that sounds correct.

**Comment by pranavgaikwad** [comment]
Fixed via #337
