### ISSUE TITLE
Make CONTEXT_LINES for code snips configureable

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#282]
This will allow users to tweak the value based on how they see fit, we will still keep the default number low to keep memory utilization low.

**Comment by MdSahil-oss** [comment]
@pranavgaikwad I would like to work on this issue, Can you please explain it a bit more.

**Comment by pranavgaikwad** [comment]
@MdSahil-oss The rule engine, when creating a violation, adds a part of the source code to the output. Based on the value of a variable [here](https://github.com/konveyor/analyzer-lsp/blob/6c6dbb5f635da71e5ce5e74750f303873857c9bd/engine/engine.go#L26), it adds surrounding lines to give more context to the user. We need to make this value configureable and take it as an argument from the CLI.

**Comment by MdSahil-oss** [comment]
Thanks @pranavgaikwad for the explanation, I'll ping you if needed more info.
