### ISSUE TITLE
Replace fmt.Println in Backoff handler with logger 

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#299]
I think this is an oversight https://github.com/konveyor/analyzer-lsp/blob/7cb1d667a4088a4ba11711491ff98987ce80c3ab/jsonrpc2/backoff_handler.go#L132

We need to replace above with `b.loggeer.V(7).Info()`

**Comment by tanryberdi** [comment]
@pranavgaikwad this issue was resolved, i think? wdyt? this changes already there

**Comment by pranavgaikwad** [comment]
@tanryberdi thank you for bringing to attention, fixed via #303
