### ISSUE TITLE
Unify Conditional interface implementations to either use value or pointer types

### ISSUE THREAD

**Issue by JonahSussman** [konveyor/analyzer-lsp#301]
I was looking at the implementations of the Conditional interface the other day and saw that of the 5 types that implement it (AndCondition, ConditionEntry, OrCondition, ProviderCondition, DependencyCondition), only ProviderCondition implements the interface as a pointer:

https://github.com/konveyor/analyzer-lsp/blob/7cb1d667a4088a4ba11711491ff98987ce80c3ab/engine/conditions.go#L73-L75

https://github.com/konveyor/analyzer-lsp/blob/7cb1d667a4088a4ba11711491ff98987ce80c3ab/provider/provider.go#L359

The other types implement the interface as a value type:

https://github.com/konveyor/analyzer-lsp/blob/7cb1d667a4088a4ba11711491ff98987ce80c3ab/engine/conditions.go#L197

I was wondering if we should unify this so we either work with value types or pointers. Looking to get your thoughts @pranavgaikwad @shawn-hurley

**Comment by shawn-hurley** [comment]
The only reason, I think/thought to have a pointer receiver is if you are changing the values of the struct from a given call, if you are just using the values it is safer to not allow any side effects. 

Does the provider condition have a method that mutates it?

**Comment by shawn-hurley** [comment]
After reading the code, I think it is pretty essential to remove the pointer receiver I am a plus on doing this. @JonahSussman you want to take it?

**Comment by JonahSussman** [comment]
Will take a crack at it, thanks!
