### ISSUE TITLE
Open source dependencies added to the analysis scope when "Application and internal dependencies only" is selected

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#320]
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration: 
  - Source + Dependencies
  - cloud-readiness, linux
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

Selecting "Application and internal dependencies only" as the analysis scope doesn't seem to have any effect, as all dependencies are being added to the analysis scope judging by the results.

### How to reproduce

- Analyze tackle-test app with the configuration available in the _Environment_ section.
- Go to the issues view and filter by the tackle-testapp application.

### Expected result

Only issues related to the application source and the config-utils dependency are displayed.

### Actual result

Multiple issues related to Open Source dependencies are displayed. For example, some of them related to Spring Framework among others:

![Screenshot from 2023-09-08 11-07-31](https://github.com/konveyor/analyzer-lsp/assets/15966456/f21ef1eb-9da3-45f4-bc1a-bf85cdc8ad8e)

**Comment by rromannissen** [comment]
Just to confirm, both Maven and Git credentials were associated to the application before running the analysis.

**Comment by pranavgaikwad** [comment]
This is caused due to an issue during building the jdtls server base image, it is fixed now, we should be rebuilding all the images and this will be solved after the rebuild.

**Comment by pranavgaikwad** [comment]
Along with maven index, we also weren't passing the label selector to the right CLI in addon. Should be now fixed via https://github.com/konveyor/tackle2-addon-analyzer/pull/42

**Comment by pranavgaikwad** [comment]
This is fixed now in the latest image.
