### ISSUE TITLE
Filename doesn't contain the actual class name in which the issue was found when analyzing dependencies

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#321]
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration: 
  - Source + Dependencies
  - cloud-readiness, linux
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### Description

When an issue is found in a dependency, the filename that gets displayed only contains the JAR file name, but it doesn't point to the actual file inside the JAR in which the issue has been found.

### How to reproduce

- Analyze tackle-test app with the configuration available in the Environment section.
- Go to the issues view, Single application and filter by the tackle-testapp application.
- Select the _Java Mail API_ issue.
- The list of affected files displays `/root/.m2/repository/ch/qos/logback/logback-core/1.1.7/logback-core-1.1.7.jar` among others. 
- Click on the file.
- Issue is actually found in the LoginAuthenticator class.

### Expected result

The filename includes the LoginAuthenticator class name and full path in the package tree.

This is how Windup displays issues within a JAR file, including class name and full path in the package tree:

![Screenshot from 2023-09-08 12-05-54](https://github.com/konveyor/analyzer-lsp/assets/15966456/58fc9536-b2ad-4b6b-8bec-af54304719a4)

### Actual result

Only the JAR file name is displayed, not providing any coordinates about the class that contains the actual incidents for the given issue:

![Screenshot from 2023-09-08 11-07-31](https://github.com/konveyor/analyzer-lsp/assets/15966456/13d08354-e667-4ebf-877b-3b12c2fb02e8)

**Comment by pranavgaikwad** [comment]
This is now fixed with the changes to deps file URIs
