### ISSUE TITLE
Incidents found in different files within a JAR file are not counted individually

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#327]
### Environment

- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-2 with additional images:
  - ui_image_fqin: quay.io/ibolton/tackle2-ui:demo
  - hub_image_fqin: quay.io/jortel/tackle2-hub:demo
  - analyzer_fqin: quay.io/jortel/tackle2-addon-analyzer:demo
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration:
  - Source + Dependencies
  - eap6
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options

### How to reproduce

- Analyze tackle-test app with the configuration available in the Environment section.
- Go to the issues view, Single application and filter by the tackle-testapp application.
- Select the _Apache org.apache.{subpackage} type reference_ issue.
- The list of affected files displays `/root/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.0/spring-boot-autoconfigure-2.5.0.jar`.
- Click on the file.
- Click on different incidents on the tabs on the top.

### Expected result

Individual incidents would belong to the same file within the JAR. If that's not the case, different files should be displayed in the file list in the list of affected files in the side drawer with their corresponding filename within the JAR (see #321).

### Actual result

Incidents belonging to different files within the spring-boot-autoconfigure-2.5.0.jar JAR file are being displayed as incidents of that parent file without differentiation. 

![Screenshot from 2023-09-11 17-53-41](https://github.com/konveyor/analyzer-lsp/assets/15966456/f31f1f85-48d6-49ae-a30e-04e1f244dbad)

![Screenshot from 2023-09-11 17-44-27](https://github.com/konveyor/analyzer-lsp/assets/15966456/0f393c0c-a27c-45b5-8157-1deb10fd5c04)

![Screenshot from 2023-09-11 17-44-31](https://github.com/konveyor/analyzer-lsp/assets/15966456/3d0ea316-3b28-433f-97ba-315d7b61f9a5)

The Windup analysis lists the issue as present in multiple files within spring-boot-autoconfigure-2.5.0.jar:

![Screenshot from 2023-09-11 18-02-17](https://github.com/konveyor/analyzer-lsp/assets/15966456/97aac145-d4e5-4a31-a6fd-9be644bbf55e)

**Comment by pranavgaikwad** [comment]
We have partially solved this problem, we need to also strip the leading paths to application source from file URIs and only return the relative paths to the file from base location.

**Comment by pranavgaikwad** [comment]
This is now fixed with the change to file URIs.
