### ISSUE TITLE
[BUG] CommonJ related issues are being found when the library is not being used by the analyzed application or its dependencies

### ISSUE THREAD

**Issue by rromannissen** [konveyor/analyzer-lsp#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3-alpha5

### Priority

Critical

### Current Behavior

Analysis is finding CommonJ related issues in the _org.springframework.spring-tx:5.3.7_ dependency from the _tackle-testapp_ application. Examining the library reveals that the CommonJ API is not being used in the code for the library. For example, the analyzer found an incident of the issue _Replace CommonJ WorkManager with a JCA Resource Adapter_ (commonj-05000) in _org.springframework.jca.support.ResourceAdapterFactoryBean_:

![Screenshot from 2023-09-29 18-31-21](https://github.com/konveyor/analyzer-lsp/assets/15966456/54c31663-5504-481e-bfaf-5121afc60182)

The rule [commonj-05000](https://github.com/konveyor/rulesets/blob/5e69b8dec1cee57b2dc2b579e41a412a25be11b3/default/generated/eap6/26-commonj.windup.yaml#L85) looks for references to the class _commonj.work.WorkManager_ via the pattern construct. Nevertheless, that class is never referenced in the  _org.springframework.jca.support.ResourceAdapterFactoryBean_ class, as [the import it does for the WorkManager class actually comes from the JCA Resource Adapter instead](https://github.com/spring-projects/spring-framework/blob/v5.3.7/spring-tx/src/main/java/org/springframework/jca/support/ResourceAdapterFactoryBean.java#L23).

Same happens with the rule [commonj-03000](https://github.com/konveyor/rulesets/blob/5e69b8dec1cee57b2dc2b579e41a412a25be11b3/default/generated/eap6/26-commonj.windup.yaml#L44) for the _io.micrometer.micrometer-core:1.7.0_ dependency in the class _io.micrometer.core.instrument.binder.httpcomponents.MicrometerHttpClientInterceptor_, [although this time the import for the Timer class is for _io.micrometer.core.instrument.Timer_](https://github.com/micrometer-metrics/micrometer/blob/v1.7.0/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/httpcomponents/MicrometerHttpClientInterceptor.java#L22)

The analysis is wrongly finding incidents for the following issues:

- Migrate commonj.timers.Timer to Java EE javax.ejb.Timer (commonj-03000)
- Replace CommonJ WorkManager with a JCA Resource Adapter (commonj-05000)
- Commonj WorkManager API (commonj-06000)
- CommonJ WorkManager API Exception (commonj-07000)

In fact, no CommonJ dependencies are being found by the analyzer, or at least they are not listed for the given application:

![Screenshot from 2023-09-29 18-51-18](https://github.com/konveyor/analyzer-lsp/assets/15966456/467c83bd-256e-4737-86be-18d8de052be3)

### Expected Behavior

No incidents should have been found for the listed issues in the tackle-testapp when running the analysis with the provided configuration.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Analyze tackle-test app with the configuration available in the Environment section.
2. Go to the issues view, Single application and filter by the tackle-testapp application.

### Environment

```markdown
- Fedora 36
- minikube v1.31.2 (--driver=kvm2 --memory=10g --cpus=3)
- Konveyor 0.3 alpha-5
- [tackle-testapp](https://github.com/konveyor/tackle-testapp) application
- Analysis configuration:
  - Source + Dependencies
  - eap6
  - Application and all dependencies, including known Open Source libraries
  - No custom rules
  - No additional advanced options
```

**Comment by pranavgaikwad** [comment]
This is fixed via https://github.com/konveyor/java-analyzer-bundle/pull/72
