### ISSUE TITLE
[BUG] Some dependencies not being detected as open source

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0-alpha.5

### Priority

Critical

### Current Behavior

Some dependencies are not being detected as open source, and therefore being analyzed when using scope _Application and internal dependencies only_ and mode _Source + dependencies_.

See for instance the following screenshot, in which an issue is being detected for a known library, despite the analysis not including known libraries:
![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/5307a9ed-2013-4128-9ff4-ab61ac6aa2f9)

### Expected Behavior

When analyzing an application with scope _Application and internal dependencies only_, only the application code and its internal dependencies should be analyzed, without any known libraries (like the `javaee-api` library in this case).

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Using the given environment, analyze the [sample.daytrader7 app (master branch)](https://github.com/WASdev/sample.daytrader7) with _Source + dependencies_ mode and _Application and internal dependencies only_ scope.
2. Notice how some known dependency libraries are included for analysis.

### Environment

```markdown
* Fedora 38
* minikube version: v1.31.2
* Konveyor 0.3.0-alpha.5
* [sample.daytrader7 app (master branch)](https://github.com/WASdev/sample.daytrader7)
* Analysis configuration:
** Source code + dependencies
** eap8, quarkus, openjdk17, azure, cloud-readiness, camel3
** Application and internal dependencies only
** No custom rules
** No additional advanced options
```

**Comment by shawn-hurley** [comment]
Is this in the [list](https://github.com/konveyor/java-analyzer-bundle/blob/main/hack/maven.default.index), and if it is supposed to be, I wonder if the pulling things from maven is not working?

**Comment by pranavgaikwad** [comment]
@shawn-hurley I think this issue has to be because of failing dependency flow in multi-module. @jmle can you please confirm if this is fixed, I think it should be.

**Comment by jmle** [comment]
Cannot reproduce this anymore - closing
