### ISSUE TITLE
[BUG] Issue description/message not appearing sometimes

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0-alpha.5

### Priority

Major

### Current Behavior

Sometimes the description of the rule does not appear in the view. See for instance:
![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/73e37622-bba6-4b10-94e4-a49a9c7822d8)

### Expected Behavior

A description should appear in the view:

> Update artifact dependency by replacing the `javax.{renamed-a}-api` artifactId with `jakarta.{renamed-a}-api`

See windup result:
![image](https://github.com/konveyor/analyzer-lsp/assets/4527008/b03edde8-76ca-4d9f-a162-9a0e77795c03)

### How Reproducible

Sometimes

### Steps To Reproduce

1. In the given environment, analyze the application with the given configuration.
2. Look for issue "javax.{renamed-a} javax.{renamed-a}-api artifactId has b" with rule id `javax-to-jakarta-dependencies-00002`
3. Description is missing.

### Environment

```markdown
* Fedora 38
* minikube version: v1.31.2
* Konveyor 0.3.0-alpha.5
* [sample.daytrader7 app (master branch)](https://github.com/WASdev/sample.daytrader7)
* Analysis configuration:
** Source code + dependencies
** eap8, quarkus, openjdk17, azure, cloud-readiness, camel3
** Application and internal dependencies only
** No custom rules
** No additional advanced options
```

**Comment by shawn-hurley** [comment]
I am pretty sure that this is happening because the regex searches are not looking across the complete 10ish lines of the code snip. need to move this to focus on the single line that is matching.

**Comment by shawn-hurley** [comment]
Actually, let me be more precise, the message for an incident can be interpolated, but the description can not be. 

For this particular one, I am noticing that a lot of the JMSWebsphere rules are failing in the shim most likely because the messages are not being set correctly

**Comment by pranavgaikwad** [comment]
I am going to close this as we have largely fixed how we are interpolating vars in incidents. I dont think we will solve the description issue.
