### ISSUE TITLE
Re-design the output, such that we get all the rules that were executed

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#38]

**Comment by rromannissen** [comment]
Windup provides something like this, which is especially useful in the context of custom rules development:

![Screenshot from 2022-11-11 16-58-41](https://user-images.githubusercontent.com/15966456/201380657-1e37503a-a4cc-4839-84de-16b6ebcb3f2e.png)

This could help us understand what information has been commonly consumed by users, but I guess we don't need to maintain everything.

**Comment by shawn-hurley** [comment]
Closing and tracking in #81
