### ISSUE TITLE
[BUG] Property resolution leads to SEGV when POM has no own props

### ISSUE THREAD

**Issue by ascheman** [konveyor/analyzer-lsp#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

How can I get it? I am using Analyzer-LSP directly!

### Priority

Blocker

### Current Behavior

When analysing a Java POM with a dependency as a property, analyzer tries to resolve the property in the same POM. If the POM contains no properties at all, this leads to a segmentation violation (in [line 141 of `provider/internal/java/dependeny.go`](https://github.com/konveyor/analyzer-lsp/blob/9369083d47c8b056775300b38adeae856612f397/provider/internal/java/dependency.go#L141)):

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b3ddc]
```

### Expected Behavior

Try to resolve property via parent POM (hierarchy) or leave unresolved otherwise (which [is the default, if the property cannot be found in an existing POM property list](https://github.com/konveyor/analyzer-lsp/blob/9369083d47c8b056775300b38adeae856612f397/provider/internal/java/dependency.go#L142)).

### How Reproducible

Always (Default)

### Steps To Reproduce

Prepare a project with POM like this.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>some-project</groupId>
    <artifactId>some-artifact</artifactId>
    <version>does-not-matter</version>
    
    <dependencies>
        <dependency>
            <groupId>some-dep-group</groupId>
            <artifactId>some-dep-artifact</artifactId>
            <version>${cannot-be-resolved}</version>
        </dependency>
    </dependencies>
</project>
``` 

And analyze it.

### Environment

```markdown
Have to provide a minimal example ...
```

**Comment by jmle** [comment]
@ascheman thank you for filling this bug! Do you want to give it a shot and fix it? Otherwise I'll pick it up.

**Comment by ascheman** [comment]
Thanks for picking this up, @jmle - I have a workaround in progress (at least to avoid the SEGV) and can contribute it soon.

In general I would be happy to provide a test case to avoid regressions for this in the future, and of course a full solution. But I need some more time to set this up. Therefore I would appreciate some help.

**Comment by jmle** [comment]
Cool @ascheman, feel free to ask any questions in the #konveyor-dev slack channel

**Comment by ascheman** [comment]
Would be happy to proceed there: https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1698750038252959

**Comment by ascheman** [comment]
It is hard to reproduce this error now - it only occurs during fallback resolution of POM dependencies which is no longer the case when `mvn dependency:tree` works as expected (cf. #393). I was trying to [provide an integration test](https://github.com/konveyor/analyzer-lsp/commit/b54f9b67a28b754fe9961381fdb990498a9079eb) by making the examples/java project a Multi-Module project with a submodule without properties. However, the respective code is not used during a dependency analysis any longer. 

Will try to provide a unit test for this.
