### ISSUE TITLE
[BUG] Java / Maven analysis does not work if the project does not compile with JDK 17

### ISSUE THREAD

**Issue by ascheman** [konveyor/analyzer-lsp#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

60c4fcbe62658708fb4290cbdcb24b75e9619814

### Priority

Blocker

### Current Behavior

If a Maven project does not compile with JDK 17, the analysis will abort.

### Expected Behavior

Make it work with misc. Java / JDK versions. Perhaps some hint for the desired Java version is necessary?

### How Reproducible

Always (Default)

### Steps To Reproduce

Project which is incompatible with JDK 17 needed, e.g., by calling `sun.misc.Unsafe`

### Anything else?

If the call to Maven fails, it would be great to get the (full) output of the background process for failure analysis.

**Comment by ascheman** [comment]
Check [Slack](https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1698772458802029?thread_ts=1698750038.252959&cid=C04QZJFQ0UA) for some discussion

**Comment by ascheman** [comment]
The compile goal can be dropped from the Maven call when using a newer version of Maven (locally tested with Maven 3.9.5). According to @jmle the compile goal needed to be added as Maven was not properly analysing dependencies for modules in a multi-module build. Of course, this didn't work with Maven 3.6.3 (as installed by [Java-Analyzer-Bundle](https://github.com/konveyor/java-analyzer-bundle/blob/9cb5a19d87531487df378afbb37de4c60d16ae87/Dockerfile#L11)).

**Comment by shawn-hurley** [comment]
I worry about trying to use a version that is un-installable in UBI9. Not to say we can't figure it out, but did want to note the limitation that we would have

This is an excellent thing for us to look in. Is there a specific version or syntax you are hitting for my edification,

**Comment by ascheman** [comment]
I don't understand the limitation? You cannot install it with `dnf`? 
Then why do you [setup python packages in other places](https://github.com/ascheman/analyzer-lsp/blob/main/Dockerfile#L25-L25)? Isn't this also beyond UBI installation processes?

Regarding Maven/Dependency computation: Find the maximum version which is possible (perhaps it is not required to get the latest 3.9.x, maybe 3.8.x or something will do as well)? Perhaps it is even possible to use Maven 3.6 and explicitely use the dependency plugin in version 3.x?

In general, as we have [seen today](https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1698772458802029?thread_ts=1698750038.252959&cid=C04QZJFQ0UA), in the future there will be more software packages required which are not part of an UBI distribution. Some projects will not even compile with Java 17. So you will have to provide different Java versions (maybe even down to < 8 for very old migration projects). 

Maybe you will start thinking about those challenges early?

**Comment by shawn-hurley** [comment]
Installing a; specific version of maven and using a specific JDK was quite a problem IIRC in the UBI image to get things set up. I am just worried about it, and wanted to let folks know who may pick this issue up, that this could be a concern.
