### ISSUE TITLE
Pipelining in Rules

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#4]
We need to enable and support pipelining in the rule

This will track all the work left outstanding:

- [x] Initial PR: #20 
- [x] #22
- [x] #23
- [x] #24

**Comment by pranavgaikwad** [comment]
As all four issues under this initial pipelining milestone have met, I am closing this. This issue only addresses pipelining within conditions of a rule. For pipelining within rules, please see #50
