### ISSUE TITLE
[BUG] Analysis fails for OpenMRS Core app

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Critical

### Current Behavior

Analysis fails with a panic for https://github.com/openmrs/openmrs-core

### Expected Behavior

Analysis should not fail

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Run analysis for https://github.com/openmrs/openmrs-core
2. Choose OpenJDK as target
3. Choose Source + Dependencies mode (this is equivalent to default "full" mode in kantra)

### Environment

```markdown
- **Analyzer Image SHA** latest
- **JDTLS  base image SHA**
- **Provider Settings JSON**
```

**Comment by jmle** [comment]
Fixed in https://github.com/konveyor/analyzer-lsp/pull/425, I think this can be closed now

**Comment by pranavgaikwad** [comment]
Closing based on previous comment.
