### ISSUE TITLE
[BUG] "konveyor-analyzer-dep --help" keeps running instead of showing help and stopping

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0-beta2

### Priority

Minor

### Current Behavior

When running `konveyor-analyzer-dep --help`, the command shows the help and keeps running instead of exiting.

### Expected Behavior

The command should show the help and exit.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Run `[docker|podman] run -ti --entrypoint /bin/bash <latest analyzer-lsp image>`
2. Run `konveyor-analyzer-help` within the container.

### Environment

```markdown
- Fedora 38
- Latest analyzer-lsp image
```

**Comment by shawn-hurley** [comment]
@Vickysomtee all yours!

**Comment by jmle** [comment]
Hey @Vickysomtee, thank you for taking a look. The log messages that appear after the "Flags" section indicate that the bin is actually running a dependency analysis, and that shouldn't happen. That is what should be fixed.

**Comment by Vickysomtee** [comment]
@shawn-hurley Thanks for the pointers, I have a better understanding. 

One quick question about this. 

> We also need to handle the case when help is specifcally called like:[} else if rootCmd.Flags().Changed("help") {](https://github.com/konveyor/analyzer-lsp/blob/f6cdf400bf2c7e236b050f31300e9e504e241d78/cmd/analyzer/main.go#L73-L74)

What should happen when help is specifically called

**Comment by shawn-hurley** [comment]
Print the help text, and then exit would be what would be best

**Comment by Vickysomtee** [comment]
> Print the help text, and then exit would be what would be best

@shawn-hurley I am not sure I understood what you meant by `Print the help text` but I created a [draft PR](https://github.com/konveyor/analyzer-lsp/pull/468) so you can review
