### ISSUE TITLE
Log yaml parsing errors when parsing rules from a file

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#476]
This will be useful to find issues with bad YAML files without going unnoticed like one I found here https://github.com/konveyor/rulesets/pull/58

Add log.Error(err, ...) here:

https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/parser/rule_parser.go#L94
https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/parser/rule_parser.go#L183

**Comment by verma-kunal** [comment]
Hi @pranavgaikwad , hope you are doing well! I'm actually new to the project & was pointed towards contributing to this part of the project to get started!
I'm a beginner in Go, so would be great if you could point me in the right direction to get started with this issue. 
Thanks

**Comment by pranavgaikwad** [comment]
@verma-kunal Thanks! Fixing this issue is easy. All you have to do is add two log statements (like https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/parser/rule_parser.go#L53) to capture errors in two locations I shared above. 

Important thing is to be able to test it. You need a bad rules file that can generate this error (read more about [rules here](https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/docs/rules.md)). To test it, I recommend that you rebuild the container with your changes as explained [here](https://github.com/konveyor/analyzer-lsp/tree). You can change the file [rule-example.yaml](https://github.com/konveyor/analyzer-lsp/blob/01d07083f8033531ca1666b899329ed47cb8ad24/rule-example.yaml) and re-build the container. 

I would also get familiar with running from source code as that helps understand providers better. See [running from source code](https://github.com/konveyor/analyzer-lsp/tree/01d07083f8033531ca1666b899329ed47cb8ad24#running-from-source-code). 

We are currently short on technical / developer docs. If you find areas where docs need improvement, please do not hesitate to create an issue.

**Comment by verma-kunal** [comment]
Thanks for all the pointers here @pranavgaikwad ! I think i'll start with understanding the provider's structure by running the source code as you mentioned, so that i get a better idea! Will proceed from there

> We are currently short on technical / developer docs. If you find areas where docs need improvement, please do not hesitate to create an issue.

Sure, noted! can you pls assign the issue to me? 
Thanks again

**Comment by verma-kunal** [comment]
Hey @pranavgaikwad , just wanted to give a heads-up that i'll be working on this after Feb 2nd, as i'm traveling before that!
I hope thats alright.
Thanks

**Comment by Vickysomtee** [comment]
@verma-kunal if by any circumstance you will no longer be able to work on the issue due to your schedule, do well to signify so someone else can work on it

**Comment by verma-kunal** [comment]
Hi @Vickysomtee , i may not be able to take this up for another couple of days, as i've not been well since 2 days! To avoid more delay, If it seems fit, you can take this up!

Thanks

**Comment by Vickysomtee** [comment]
> Hi @Vickysomtee , i may not be able to take this up for another couple of days, as i've not been well since 2 days! To avoid more delay, If it seems fit, you can take this up!
> 
> Thanks

@verma-kunal Sorry about that. I will pick it up. Do take care of yourself

**Comment by Vickysomtee** [comment]
@pranavgaikwad what would be an example of a bad rule file that will suit testing the issue?

**Comment by pranavgaikwad** [comment]
@Vickysomtee any invalid YAML rules file will do. Use rule-example.yaml in, maybe remove a space from any one of the rules to malform the indentation.
