### ISSUE TITLE
Demo rules under `demo-rules` directory should be removed

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#480]
Rules under [demo-rules](https://github.com/konveyor/analyzer-lsp/tree/main/demo-rules) are no longer needed. This was added back in the  day to quickly test the java provider and is not in use. 

Delete the directory, open a PR, make sure CI passes. To see the CI results, see `Demo Testing / test ` workflow on the PR.

**Comment by UtkarshUmre** [comment]
Hey @pranavgaikwad this looks like a good first issue to me. Could you please assign this to me?

**Comment by Vickysomtee** [comment]
@UtkarshUmre you neccessarily don't need to wait to be assigned. You can proceed with working on the issue.
