### ISSUE TITLE
[BUG] LS not responding properly when POM file is malformed

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0

### Priority

Critical

### Current Behavior

If the pom file of the project to be analyzed is broken in any way:
- Malformed (for instance, missing the `groupId`
- Artifacts that cannot be found
- Etc...

then the java provider won't give references back at all.

### Expected Behavior

If the pom file is malformed, we should at least return an error message specifying the problem

### How Reproducible

Always (Default)

### Steps To Reproduce

Try to analyze any application with a broken POM and see how no results are returned.

**Comment by shawn-hurley** [comment]
This will be fixed with 

https://github.com/konveyor/tackle2-addon-analyzer/pull/97
https://github.com/konveyor/tackle2-addon-analyzer/pull/101

**Comment by shawn-hurley** [comment]
PR's are merged closing
