### ISSUE TITLE
[Bug] Add openapi struct fields for dependency condition

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#551]
using: https://github.com/swaggest/jsonschema-go?tab=readme-ov-file#field-tags

We should add the title, description, and pattern fields to the struct here:
https://github.com/konveyor/analyzer-lsp/blob/feature/use-open-api/provider/provider.go#L616-L624

You can use this as a starting point for the [semver](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) regular expression.

| Provider | Capability  | Fields     | Required | Description                                                   |
|----------|-------------|------------|----------|---------------------------------------------------------------|
|          | dependency  | name       | Yes      | Name of the dependency                                        |
|          |             | nameregex  | No       | Regex pattern to match the name                               |
|          |             | upperbound | No       | Match versions lower than or equal to                         |
|          |             | lowerbound | No       | Match versions greater than or equal to                       |

**Comment by Vickysomtee** [comment]
@shawn-hurley I am available to work on this

**Comment by shawn-hurley** [comment]
@Vickysomtee All yours if you want to work on it!

**Comment by Vickysomtee** [comment]
> We should add the title, description, and pattern fields to the struct here:
https://github.com/konveyor/analyzer-lsp/blob/feature/use-open-api/provider/provider.go#L616-L624

@shawn-hurley the url here returns 404

**Comment by shawn-hurley** [comment]
Sorry @Vickysomtee here is a better link: https://github.com/konveyor/analyzer-lsp/blob/main/provider/provider.go#L616-L624
