### ISSUE TITLE
[BUG] Discrepancy in the Effort and Tag count with tackle-testapp

### ISSUE THREAD

**Issue by kpunwatk** [konveyor/analyzer-lsp#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Major

### Current Behavior

1. analysis_on_tackletestapp":

"source": "Source code + dependencies",

"target": ["JBoss Web Server 6"],

"appName": "tackle-testapp",

"New effort": 536

"Previous effort": 2 

 

2. analysis_on_tackletestapp
"source": "Source code + dependencies",
"target": ["OpenJDK 17"],
"appName": "tackle-testapp",
"Previous effort": 4104
"New effort":  2544

### How Reproducible

Always (Default)

### Environment

```markdown
- **Analyzer Image SHA** 
- **JDTLS  base image SHA**
- **Provider Settings JSON**
```

**Comment by pranavgaikwad** [comment]
@kpunwatk  Can you please confirm if this is fixed in latest? We fixed a bunch of bugs around accuracy of incidents.

**Comment by shawn-hurley** [comment]
Closing this as this is tracked in other issues and a fix is up.
