### ISSUE TITLE
[BUG] Gradle Support - Analysis fails for gradle-multi-project-example

### ISSUE THREAD

**Issue by abrugaro** [konveyor/analyzer-lsp#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kantra version (Tested using kantra)

```
version: latest
SHA: a89ffa3bce466bb46ecc658a2b07e7d2bec69af1
image: quay.io/konveyor/kantra
```

### Priority

Undefined (Default)

### Current Behavior

Analysis of the [gradle-multi-project-example](https://github.com/konveyor/analyzer-lsp/tree/main/external-providers/java-external-provider/examples/gradle-multi-project-example) application fails.

Here you can find the analysis' outputs

[provider.txt](https://github.com/user-attachments/files/15816132/provider.txt)
[output.yaml.txt](https://github.com/user-attachments/files/15816133/output.yaml.txt)
[analysis.txt](https://github.com/user-attachments/files/15816134/analysis.txt)

### Expected Behavior

Analysis shouldn't fail for this applicaton

### How Reproducible

Always (Default)

### Steps To Reproduce

(I tested it using Kantra)

1. Donwload the gradle-multi-project-example application as zip file
2. Start an analysis by using the following command

`kantra analyze --input ~/apps/gradle-multi-project-example-master.zip --output ~/report-gradle --overwrite`

**Comment by jmle** [comment]
After taking a look at the logs, it looks like the problem comes from trying to analyze a zip file. I _think_ that at the moment we only support [these binary formats](https://github.com/konveyor/analyzer-lsp/blob/main/external-providers/java-external-provider/pkg/java_external_provider/provider.go#L28-L34) and analyzing uncompressed source code.

**Comment by abrugaro** [comment]
@jmle you're right, I can confirm that when running the analysis against an uncompressed folder it works as expected. Hence closing this issue.
