### ISSUE TITLE
[BUG] [RULES] False positive on "javax.xml.soap.SOAPElementFactory.create() must be replaced" jakarta-soap-00020

### ISSUE THREAD

**Issue by abrugaro** [konveyor/analyzer-lsp#652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5 beta 1

### Priority

Undefined (Default)

### Anything else?

Tested with Kantra b0.5 beta1
**Target:** eap8 (and others)
**Source:** none
**Source code used:** https://github.com/sonatype/nexus-public
**Rule triggered:** `jakarta-soap-00020` javax.xml.soap.SOAPElementFactory.create() must be replaced
**Report:** https://drive.google.com/file/d/1TbdLS4_728DgxbB88F7YcXw84jK2elty/view?usp=drive_link

This rule reported 6 incidents for the application, all of them were related to calls to `create` methods not related to the ` javax.xml.soap.SOAPElementFactory` class

![image](https://github.com/user-attachments/assets/8a0cf11b-2bfe-4b4a-b453-19ea5f477ea7)
Tested with Kantra b0.5 beta1
**Target:** eap8 (and others)
**Source:** none
**Source code used:** https://github.com/sonatype/nexus-public
**Rule triggered:** `jakarta-soap-00020` javax.xml.soap.SOAPElementFactory.create() must be replaced
**Report:** https://drive.google.com/file/d/1TbdLS4_728DgxbB88F7YcXw84jK2elty/view?usp=drive_link

This rule reported 6 incidents for the application, all of them were related to calls to `create` methods not related to the ` javax.xml.soap.SOAPElementFactory` class

![image](https://github.com/user-attachments/assets/8a0cf11b-2bfe-4b4a-b453-19ea5f477ea7)

![image](https://github.com/user-attachments/assets/25d1bc01-6948-4a62-ac23-a38e410ad7b4)

**Comment by dymurray** [comment]
We think some changes going in to improve on method call matching might help to improve this. @jmle is looking into this.

**Comment by dymurray** [comment]
Confirmed this is no longer an issue in 0.5.0-rc.1
