### ISSUE TITLE
[BUG] Annotation location cannot be inspected for attributes/parameters

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.5-beta1

### Priority

Critical

### Current Behavior

In the java provider, `location: ANNOTATION` cannot be inspected for particular elements (attributes within the annotation).

### Expected Behavior

We need to be able to match annotations with particular elements.

### How Reproducible

Always (Default)

### Environment

```markdown
- **Analyzer Image SHA** 
- **JDTLS  base image SHA**
- **Provider Settings JSON**
```

**Comment by dymurray** [comment]
This rule issue is impacted by this https://github.com/konveyor/rulesets/issues/86
