### ISSUE TITLE
Some java rules are not being triggered

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#71]
See [this commit](https://github.com/jmle/analyzer-lsp/commit/d00c67e6b268785d4ace0cdac5edad2386fa38ab) for test data. Both added rules should be triggered according to the test data, but I can't see any references in the results.

**Comment by shawn-hurley** [comment]
fixed here: https://github.com/konveyor/java-analyzer-bundle/pull/28

**Comment by shawn-hurley** [comment]
Waiting on: https://github.com/konveyor/java-analyzer-bundle/pull/31/files to fix this. 

We should add this as a test case
