### ISSUE TITLE
Track source as fileuri when reporting dependencies

### ISSUE THREAD

**Issue by fabianvf** [konveyor/analyzer-lsp#73]
Currently we don't point to where the dependencies are coming from, which could be a useful piece of information. We should track and report that. We should also change the `Location` field in the `dependency.Dep` to match `Location` in the rest of the code base (ie it should point somewhere in the codebase) and find a different term to report what it currently gathers for java (or add it to an extras field for arbitrary metadata)

**Comment by pranavgaikwad** [comment]
@fabianvf Did you just mean pointing to where the dependency is declared (pom.xml, go.mod) or you meant where it's actually used?

**Comment by fabianvf** [comment]
Where it's declared

**Comment by pranavgaikwad** [comment]
Location can be renamed to Type maybe?
