### ISSUE TITLE
Add ability in that java language LSP add-on to decompile jar files, if needed

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#9]
Using: https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine which can be pulled from here: https://mvnrepository.com/artifact/com.jetbrains.intellij.java/java-decompiler-engine the java LSP bundle to decompile and then re-initialize the project.

**Comment by shawn-hurley** [comment]
Must support Jar, Ear and War file types fo the Java decompilation

**Comment by pranavgaikwad** [comment]
I am moving this issue to Demo D as it requires little more work, and larger priorities for Demo C are all around getting Windup shim working.

**Comment by shawn-hurley** [comment]
After thinking about this more, I have come to a new conclusion. 

1. The work that David did is perfect and will mostly work. For the jar files that are in a given archive, we will capture them, put them in src/lib, and they will be added to the classpath. @pranavgaikwad, this will fix the thing you are looking at.
2. We will have a new Provider grpc method, which will be responsible for getting the code snip from ANY URI's that are not files (if files we can use what we already have). 
3. This new method will then, unarchive the jar (jar -xf <path_to_jar> /tmp/<golang_created_tmpfolder>, then it fernflower decompile just that given class file. 
4. There is a potential issue here, with the <location> information and I am working on solving this. I assume there is some way to map it back but I think that the provider needs to handle this either way and we can use the full URI to send this information, the new provider method will also update the URI.

**Comment by pranavgaikwad** [comment]
@shawn-hurley I do not see a problem with the approach. The decompilation time does add up...[this is something](https://github.com/konveyor/analyzer-lsp/issues/203) I need to fix in the decomp part too. By inheriting the incident limit, I think we will save ourselves significant work. In case of many incidents, I do see this increasing the overall time though if not at startup...so a way to cache a file for a run would be ideal. I think updating the URI is fine.

**Comment by fabianvf** [comment]
This seems like a good approach to me
